### Numpy

* Numpy是高性能科学计算和数据分析的基础包。它是pandas等其他各种工具的基础。
* Numpy的主要功能：
  * ndarray，一个多维数组结构，高效且节省空间
  * 无需循环对数组数据进行快速运算的数学函数
  * 读写磁盘数据的工具及操作内存映射文件的工具
  * 线性代数、随机数生成及傅里叶变换功能
  * 用于集成C、C++等代码的工具
  
安装：

```script
pip install numpy
```

导入方式：

```python
import numpy as np
```

国内源：

* 中国科技大学 https://pypi.mirrors.ustc.edu.cn/simple/
* 清华 https://pypi.tuna.tsinghua.edu.cn/simple

安装完成后请尝试以下代码：

In [5]:
import numpy as np

np.array([1, 2, 3, 4, 5])   # 创建一个ndarray

for i in _:     # 此行的"_"代表上一行的返回值
    print(i)

请比较此处上下相关的两部分代码！```np.array```比```list```有以下好处：

* 运算速度比列表快
* 内存占用比列表小

In [3]:
# 下面代码显示np.array的类型
import numpy as np

a = np.array([1, 2, 3, 4, 5])
print(type(a))     # numpy.ndarray

<class 'numpy.ndarray'>


In [4]:
# 下面的代码查看对象所占的数据类型
import sys

a = list(range(100))
print(sys.getsizeof(a))     # 显示占用856个字节

b = np.array(range(100))
print(sys.getsizeof(b))     # 显示占用504个字节

856
504


In [15]:
# 以随机数方式创建价格列表及数量列表
import random
import numpy as np

# 生成价格列表
pricelist = [round(random.uniform(10.0, 100.0), 2) for i in range(20)]
pricelist_np = np.array(pricelist)

# 生成数量列表
numlist = [random.randint(1, 10) for i in range(20)]
numlist_np = np.array(numlist)

def getTotal(plist, nlist):
    total = 0

    for i, j in zip(plist, nlist):
        total += i * j
        
    return total

In [18]:
# 求和
getTotal(pricelist, numlist)

5215.46

In [20]:
timeit getTotal(pricelist, numlist)

1.38 µs ± 18.1 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [17]:
# 求和，矢量积，笛卡尔积
np.dot(pricelist_np, numlist_np)

5215.459999999999

In [21]:
timeit np.dot(pricelist_np, numlist_np)

1.62 µs ± 8.05 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [24]:
timeit (pricelist_np * numlist_np).sum()

3.21 µs ± 47.5 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [27]:
pricelist_np

array([24.19, 93.12, 24.17, 61.89, 35.63, 48.79, 50.46, 97.21, 61.63,
       37.63, 72.71, 78.63, 19.23, 70.61, 47.02, 94.35, 36.9 , 70.86,
       35.34, 64.09])

In [28]:
# ndarray的其他算法
pricelist_np + 1

array([25.19, 94.12, 25.17, 62.89, 36.63, 49.79, 51.46, 98.21, 62.63,
       38.63, 73.71, 79.63, 20.23, 71.61, 48.02, 95.35, 37.9 , 71.86,
       36.34, 65.09])

In [29]:
# 查看数据类型，ndarray必须是相同的数据类型
pricelist_np.dtype

dtype('float64')

Numpy的ndarray

* dtype
  * bool_, int(8, 16, 32, 64), uint(8, 16, 32, 64), float(16, 32, 64)
  * 类型转换：astype()
* 创建ndarray: np.array()
  * array()，将列表转换为数组，可指定dtype
  * arange()，numpy版的range()，支持浮点数
  * linspace(), 类似arange()，第三个参数为数组长度
  * zeros()，创建0数组
  * ones()，创建1数组
  * empty()，创建空数组，随机值
  * eye()，根据指定边长创建单位矩阵
* 为什么要使用ndarray:
  * examp 1：已知若干公司的美元市值，求其人民币市值
  * examp 2：已知购物车中商品的价格及件数，求总价
* ndarray可以是多维数组，但元素的类型必须相同
* 常用属性：
  * T，数组的转置
  * dtype，数组元素的数据类型
  * size，数组元素的个数
  * ndim，数组的维度数
  * shape，数组维度的大小

In [2]:
# 创建nparray
import numpy as np

a = np.arange(100)
a.shape

(100,)

In [8]:
# 创建多维数组
import numpy as np

a = np.array([[1, 2, 3], [4, 5, 6]])
a.size
a.shape
a.ndim
a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

numpy基础25分钟处